### ISSUE TITLE
Logistic regression LSM model shows only high value

### ISSUE THREAD

**Issue by talhamalik211** [emrehanks/R-ArcGIS-LSM_ToolPack#6]
There is issue with me when i run logistic regression it show only high value. Please help me to solve this issue.

**Comment by emrehanks** [comment]
Hi, please try the Sample Data which give on this Github web page. If you meet the same problem again then I'll try to help you.

**Comment by talhamalik211** [comment]
Thank you for your reply. Brother my Master's thesis is stuck because of
this problem. I had tried many time bus only in the logistic regression the
LSM show only high value.

**Comment by talhamalik211** [comment]
This issue only face only in mine one data set. I also used this tool
logistic regression for another data set  but it dosen't show and kind of
problem. Please can you tell me that what kind of possibility that  cause
this kind of issue in LSM of LOGISTIC regression. So that i can check that
issue in my data .

**Comment by emrehanks** [comment]
hi, apparently the main problem is caused by your data. I recommend you increased data size and use raw data (I mean that nonclassified data).

**Comment by talhamalik211** [comment]
Thank you brother for your reply. I will try this if it solved the problem
then i will inform you.

**Comment by talhamalik211** [comment]
thank you soo much brother my problem has been solved. i will acknowledge
you in my work.

**Comment by emrehanks** [comment]
Your welcome. Best regards, EKS...
